"""Initial migration with correct user_id

Revision ID: f7a709ecd6bf
Revises: 
Create Date: 2025-07-28 04:16:54.307493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a709ecd6bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('task_text', sa.String(), nullable=True),
    sa.Column('task_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_id'), 'task_events', ['id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_events_task_user_id'), 'task_events', ['task_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_events_task_user_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_table('task_events')
    # ### end Alembic commands ###
